- hosts: hadoop
  become: yes
  tasks:
    - name: Start Docker services
      command: docker-compose up -d
      args:
        chdir: /home/squalala/hadoop_cluster

    - name: Check containers
      command: docker ps
