global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hadoop-namenode'
    static_configs:
      - targets: ['namenode:9870']

  - job_name: 'hadoop-datanode'
    static_configs:
      - targets: ['datanode1:9864', 'datanode2:9864']

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
