name: Hadoop Project CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov flake8
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      run: |
        pytest --cov=src
        
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Data Ingestion image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.ingestion
        push: true
        tags: username/hadoop-data-ingestion:latest
        
    - name: Build and push Data Processing image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.processing
        push: true
        tags: username/hadoop-data-processing:latest
        
    - name: Build and push API Interaction image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.api
        push: true
        tags: username/hadoop-api-interaction:latest
        
    - name: Build and push Visualization image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.visualization
        push: true
        tags: username/hadoop-visualization:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        
    - name: Run ansible playbook
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ansible-playbook -i ansible/inventory.ini ansible/deploy-hadoop.yml
