name: Hadoop Complete Cluster CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  hadoop-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show Docker and Compose version
        run: |
          docker --version
          docker compose version || docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # (Login DockerHub supprimé)

      - name: Build Hadoop images
        run: |
          docker compose build || docker-compose build

      - name: Run Complete Deployment Script
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh --ordered

      - name: Show cluster status
        run: |
          ./deploy.sh --status

      - name: Cleanup all Docker resources (optional)
        if: always()
        run: |
          docker stop $(docker ps -aq) || true
          docker system prune -af --volumes || true
